version: '3'

services:

  test:
    container_name: auth-server-test
    image: alesr/restfulgopher-auth-server-test
    networks:
      - restfulgophernet
    build:
      context: .
      dockerfile: resources/server/test/Dockerfile

  server:
    container_name: auth-server
    image: alesr/restfulgopher-auth-server
    networks:
      - restfulgophernet
    build:
      context: .
      dockerfile: resources/server/prod/Dockerfile

  mongodb:
    container_name: auth-db
    image: alesr/restfulgopher-db
    build:
      context: .
      dockerfile: resources/mongodb/Dockerfile
    networks:
      - restfulgophernet
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
    expose:
      - "27017"
    ports:
      - "27017:27017"

  nginx:
    container_name: auth-nginx
    image: alesr/restfulgopher-auth-nginx
    ports:
      - "80:80"
    links:
      - server:server
    depends_on:
      - server
    networks:
      - restfulgophernet
    build:
      context: .
      dockerfile: resources/nginx/Dockerfile

networks:
  restfulgophernet:
